# .github/workflows/deploy.yml
name: CI/CD with Telegram

on:
  push:
    branches: [main]

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          yarn install
          yarn build

      - name: Notify Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Деплой завершён: ${{ github.repository }} на ветке ${{ github.ref_name }}"
